name: test

on:
  push:
    branches:
        - main
  pull_request:

env:
  ENGINE_API_URL: ${{ secrets.ENGINE_API_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          command: bash go.sh
